# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Login.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Login.proto',
  package='com.HHGame.Login',
  serialized_pb='\n\x0bLogin.proto\x12\x10\x63om.HHGame.Login\"\x1d\n\x0cHeartRequest\x12\r\n\x05state\x18\x01 \x02(\x08\"\x1e\n\rHeartResponse\x12\r\n\x05state\x18\x01 \x02(\x08\")\n\x0cLoginRequest\x12\x0b\n\x03uid\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\"\x1e\n\rLoginResponse\x12\r\n\x05state\x18\x01 \x02(\x08')




_HEARTREQUEST = _descriptor.Descriptor(
  name='HeartRequest',
  full_name='com.HHGame.Login.HeartRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Login.HeartRequest.state', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=62,
)


_HEARTRESPONSE = _descriptor.Descriptor(
  name='HeartResponse',
  full_name='com.HHGame.Login.HeartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Login.HeartResponse.state', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=64,
  serialized_end=94,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='com.HHGame.Login.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='com.HHGame.Login.LoginRequest.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='com.HHGame.Login.LoginRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=96,
  serialized_end=137,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='com.HHGame.Login.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Login.LoginResponse.state', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=139,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['HeartRequest'] = _HEARTREQUEST
DESCRIPTOR.message_types_by_name['HeartResponse'] = _HEARTRESPONSE
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE

class HeartRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEARTREQUEST

  # @@protoc_insertion_point(class_scope:com.HHGame.Login.HeartRequest)

class HeartResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEARTRESPONSE

  # @@protoc_insertion_point(class_scope:com.HHGame.Login.HeartResponse)

class LoginRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINREQUEST

  # @@protoc_insertion_point(class_scope:com.HHGame.Login.LoginRequest)

class LoginResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINRESPONSE

  # @@protoc_insertion_point(class_scope:com.HHGame.Login.LoginResponse)


# @@protoc_insertion_point(module_scope)
