# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Pk.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Pk.proto',
  package='com.HHGame.Pk',
  serialized_pb='\n\x08Pk.proto\x12\rcom.HHGame.Pk\"%\n\x08PkPlayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pos\x18\x02 \x01(\x05\"1\n\x05PkPai\x12\x0b\n\x03pos\x18\x01 \x02(\x05\x12\x0c\n\x04type\x18\x02 \x02(\x05\x12\r\n\x05value\x18\x03 \x02(\x05\"!\n\x10\x45nterGameRequest\x12\r\n\x05state\x18\x01 \x02(\x08\"L\n\x11\x45nterGameResponse\x12\r\n\x05state\x18\x01 \x02(\x08\x12(\n\x07players\x18\x03 \x03(\x0b\x32\x17.com.HHGame.Pk.PkPlayer\"\x1f\n\x0eReadyPkRequest\x12\r\n\x05state\x18\x01 \x02(\x08\" \n\x0fReadyPkResponse\x12\r\n\x05index\x18\x01 \x02(\x05\"Q\n\rFaPaiResponse\x12\r\n\x05state\x18\x01 \x02(\x08\x12\r\n\x05\x66irst\x18\x02 \x02(\x05\x12\"\n\x04pais\x18\x03 \x03(\x0b\x32\x14.com.HHGame.Pk.PkPai\"\x1f\n\rDecideRequest\x12\x0e\n\x06\x64\x65\x63ide\x18\x01 \x02(\x05\"u\n\x0e\x44\x65\x63ideResponse\x12\x0e\n\x06\x64\x65\x63ide\x18\x01 \x02(\x05\x12\r\n\x05state\x18\x02 \x01(\x08\x12\x0b\n\x03pos\x18\x03 \x01(\x05\x12\x13\n\x0b\x61\x64\x64OrRemove\x18\x04 \x01(\x08\x12\"\n\x04pais\x18\x05 \x01(\x0b\x32\x14.com.HHGame.Pk.PkPai\"9\n\rChuPaiRequest\x12\x0b\n\x03num\x18\x02 \x02(\x05\x12\r\n\x05value\x18\x03 \x02(\x05\x12\x0c\n\x04pais\x18\x04 \x02(\t\"9\n\x0e\x43huPaiResponse\x12\x0b\n\x03pos\x18\x01 \x02(\x05\x12\x0b\n\x03num\x18\x02 \x02(\x05\x12\r\n\x05value\x18\x03 \x02(\x05\"\x18\n\tChuPaiPos\x12\x0b\n\x03pos\x18\x01 \x02(\x05\"\x18\n\tDecidePos\x12\x0b\n\x03pos\x18\x01 \x02(\x05')




_PKPLAYER = _descriptor.Descriptor(
  name='PkPlayer',
  full_name='com.HHGame.Pk.PkPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.HHGame.Pk.PkPlayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='com.HHGame.Pk.PkPlayer.pos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=64,
)


_PKPAI = _descriptor.Descriptor(
  name='PkPai',
  full_name='com.HHGame.Pk.PkPai',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='com.HHGame.Pk.PkPai.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.HHGame.Pk.PkPai.type', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.HHGame.Pk.PkPai.value', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=66,
  serialized_end=115,
)


_ENTERGAMEREQUEST = _descriptor.Descriptor(
  name='EnterGameRequest',
  full_name='com.HHGame.Pk.EnterGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Pk.EnterGameRequest.state', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=150,
)


_ENTERGAMERESPONSE = _descriptor.Descriptor(
  name='EnterGameResponse',
  full_name='com.HHGame.Pk.EnterGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Pk.EnterGameResponse.state', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players', full_name='com.HHGame.Pk.EnterGameResponse.players', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=228,
)


_READYPKREQUEST = _descriptor.Descriptor(
  name='ReadyPkRequest',
  full_name='com.HHGame.Pk.ReadyPkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Pk.ReadyPkRequest.state', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=230,
  serialized_end=261,
)


_READYPKRESPONSE = _descriptor.Descriptor(
  name='ReadyPkResponse',
  full_name='com.HHGame.Pk.ReadyPkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='com.HHGame.Pk.ReadyPkResponse.index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=263,
  serialized_end=295,
)


_FAPAIRESPONSE = _descriptor.Descriptor(
  name='FaPaiResponse',
  full_name='com.HHGame.Pk.FaPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Pk.FaPaiResponse.state', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first', full_name='com.HHGame.Pk.FaPaiResponse.first', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pais', full_name='com.HHGame.Pk.FaPaiResponse.pais', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=297,
  serialized_end=378,
)


_DECIDEREQUEST = _descriptor.Descriptor(
  name='DecideRequest',
  full_name='com.HHGame.Pk.DecideRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decide', full_name='com.HHGame.Pk.DecideRequest.decide', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=380,
  serialized_end=411,
)


_DECIDERESPONSE = _descriptor.Descriptor(
  name='DecideResponse',
  full_name='com.HHGame.Pk.DecideResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decide', full_name='com.HHGame.Pk.DecideResponse.decide', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='com.HHGame.Pk.DecideResponse.state', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='com.HHGame.Pk.DecideResponse.pos', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addOrRemove', full_name='com.HHGame.Pk.DecideResponse.addOrRemove', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pais', full_name='com.HHGame.Pk.DecideResponse.pais', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=413,
  serialized_end=530,
)


_CHUPAIREQUEST = _descriptor.Descriptor(
  name='ChuPaiRequest',
  full_name='com.HHGame.Pk.ChuPaiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='com.HHGame.Pk.ChuPaiRequest.num', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.HHGame.Pk.ChuPaiRequest.value', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pais', full_name='com.HHGame.Pk.ChuPaiRequest.pais', index=2,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=532,
  serialized_end=589,
)


_CHUPAIRESPONSE = _descriptor.Descriptor(
  name='ChuPaiResponse',
  full_name='com.HHGame.Pk.ChuPaiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='com.HHGame.Pk.ChuPaiResponse.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='com.HHGame.Pk.ChuPaiResponse.num', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.HHGame.Pk.ChuPaiResponse.value', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=591,
  serialized_end=648,
)


_CHUPAIPOS = _descriptor.Descriptor(
  name='ChuPaiPos',
  full_name='com.HHGame.Pk.ChuPaiPos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='com.HHGame.Pk.ChuPaiPos.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=650,
  serialized_end=674,
)


_DECIDEPOS = _descriptor.Descriptor(
  name='DecidePos',
  full_name='com.HHGame.Pk.DecidePos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='com.HHGame.Pk.DecidePos.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=676,
  serialized_end=700,
)

_ENTERGAMERESPONSE.fields_by_name['players'].message_type = _PKPLAYER
_FAPAIRESPONSE.fields_by_name['pais'].message_type = _PKPAI
_DECIDERESPONSE.fields_by_name['pais'].message_type = _PKPAI
DESCRIPTOR.message_types_by_name['PkPlayer'] = _PKPLAYER
DESCRIPTOR.message_types_by_name['PkPai'] = _PKPAI
DESCRIPTOR.message_types_by_name['EnterGameRequest'] = _ENTERGAMEREQUEST
DESCRIPTOR.message_types_by_name['EnterGameResponse'] = _ENTERGAMERESPONSE
DESCRIPTOR.message_types_by_name['ReadyPkRequest'] = _READYPKREQUEST
DESCRIPTOR.message_types_by_name['ReadyPkResponse'] = _READYPKRESPONSE
DESCRIPTOR.message_types_by_name['FaPaiResponse'] = _FAPAIRESPONSE
DESCRIPTOR.message_types_by_name['DecideRequest'] = _DECIDEREQUEST
DESCRIPTOR.message_types_by_name['DecideResponse'] = _DECIDERESPONSE
DESCRIPTOR.message_types_by_name['ChuPaiRequest'] = _CHUPAIREQUEST
DESCRIPTOR.message_types_by_name['ChuPaiResponse'] = _CHUPAIRESPONSE
DESCRIPTOR.message_types_by_name['ChuPaiPos'] = _CHUPAIPOS
DESCRIPTOR.message_types_by_name['DecidePos'] = _DECIDEPOS

class PkPlayer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKPLAYER

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.PkPlayer)

class PkPai(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PKPAI

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.PkPai)

class EnterGameRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTERGAMEREQUEST

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.EnterGameRequest)

class EnterGameResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTERGAMERESPONSE

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.EnterGameResponse)

class ReadyPkRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _READYPKREQUEST

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.ReadyPkRequest)

class ReadyPkResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _READYPKRESPONSE

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.ReadyPkResponse)

class FaPaiResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FAPAIRESPONSE

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.FaPaiResponse)

class DecideRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DECIDEREQUEST

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.DecideRequest)

class DecideResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DECIDERESPONSE

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.DecideResponse)

class ChuPaiRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHUPAIREQUEST

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.ChuPaiRequest)

class ChuPaiResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHUPAIRESPONSE

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.ChuPaiResponse)

class ChuPaiPos(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHUPAIPOS

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.ChuPaiPos)

class DecidePos(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DECIDEPOS

  # @@protoc_insertion_point(class_scope:com.HHGame.Pk.DecidePos)


# @@protoc_insertion_point(module_scope)
